# Home Assistant Core Configuration

default_config:

# Reverse Proxy configuration for Cloudflare Tunnel
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1
    - ::1
    - 172.16.0.0/12
    - 172.19.0.0/16
    - 172.19.0.3
    - 192.168.0.0/16
    - 10.0.0.0/8

frontend:

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
